### ISSUE TITLE
Rheinland-Pfalz to_region_wide returns invalid steuernummer

### ISSUE THREAD

**Issue by Loki-Afro** [ibariens/steuernummer#7]
this bug has been intruduced via gh-5, the `to _region_wide` function (or however it is called in ruby :D)  returns a steuernummer where `p` is seperated by `/` from the `uuuu` group

Also a test failes because of this

**Comment by ibariens** [comment]
Thanks @Loki-Afro for the feedback! Seems that the Rheinland-Pfalz steuernummer changed over time on the wiki page (https://de.wikipedia.org/w/index.php?title=Steuernummer&diff=133371975&oldid=133371961). Should be fixed now.
