### ISSUE TITLE
Bug: Example in README wrong

### ISSUE THREAD

**Issue by johannesluedke** [ibariens/steuernummer#8]
I wanted to report that this example does not work as described

```
>> tax_no = Steuernummer.new("28FF0BBBUUUUP")
>> tax_no.is_valid?
=> true
```

Maybe the string is wrong?

**Comment by ibariens** [comment]
Hi @johannesluedke, sorry for the late response.
thanks for pointing this out.
the string should be indeed: 2893081508152
