### ISSUE TITLE
Potential bug: Doesn't validate legit Frankfurt Steuernummer 

### ISSUE THREAD

**Issue by johannesluedke** [ibariens/steuernummer#9]
I saw a Steuernummer on an official Finanzamt Frankfurt document of the following form 

```
26xx xxx xxxxx
```
It's in the "Vereinheitlichtes Bundesschema", but with a pattern that is not valid according to [wikipedia](https://de.wikipedia.org/wiki/Steuernummer) (5th digit is not a `0`)

But I think Finanzamt should know better then Wikipedia how to create a valid steuernummer.

Sadly I don't have any insights, what would be the valid pattern.

**Comment by ibariens** [comment]
Thanks for pointing this out @johannesluedke 

I unfortunately also can't find a better working pattern online. On [https://www.elster.de/eportal/helpGlobal?themaGlobal=wo_ist_meine_steuernummer](url) it shows the same pattern, which should be a good source. 

It would be great if you can send the number to the correct email address at: [https://www.liste-finanzamt.de/Hessen/Frankfurt.html](url) so they can tell you if they made a mistake or if the pattern got updated.

**Comment by johannesluedke** [comment]
Hi unfortunately I don't have this at hand any more because I'm not involved any more with that project.
